from cma import CMAEvolutionStrategy as cmaes
import gymnasium as gym
import numpy as np
import functools
from random import Random
from multiprocessing import Pool
import pickle
import sys
import os
import math
from hostNN import HostMultipleNN
from plot_utils import plot_weights, plot_generations

# training an NN, called HostMultipleNN, that works with other NNs, each deciding a weight the host

# executed one time for each candidate
def eval(ds, render=False):

    x = ds[0]
    hostNodes = ds[1]
    guestNodes = ds[2]
    inputType = ds[3]
    updateType = ds[4]

    cumulative_rewards = []
    weights = []

    task = gym.make("CartPole-v1")
    agent = HostMultipleNN(hostNodes, guestNodes, inputType, updateType)

    # set the weights as the value of the candidates generated by cmaes
    agent.set_weights(x)

    # each candidate tries the task 100 times, then the resulting reward is the average
    for i in range(100):
        cumulative_rewards.append(0)
        done = False
        obs, info = task.reset(seed=i, options={})
        counter = 0

        # make the guestsNN compute the weights

        agent.compute_host_weights()
        weights.append(agent.get_list_weights())
        #agent.nn_prune_weights(ds[2])

        while not done:
            output = agent.activate(obs)

            # arr[output]+=1
            if render:
                task.render()
            obs, rew, terminated, truncated, info = task.step(np.argmax(output))
            cumulative_rewards[-1] += rew

            done = terminated or truncated
        counter += 1

    return -sum(cumulative_rewards) / 100, weights


def generator(random, args):
    return np.asarray([random.uniform(args["pop_init_range"][0],
                                      args["pop_init_range"][1])
                       for _ in range(args["num_vars"])])


def generator_wrapper(func):
    @functools.wraps(func)
    def _generator(random, args):
        return np.asarray(func(random, args))

    return _generator

# multiprocessing
def parallel_val(candidates, hostNodes, guestNodes, inputType, updateType):

    with Pool(20) as p:
        # executes one eval foreach candidate
        x = p.map(eval, [[c, hostNodes, guestNodes, inputType, updateType] for c in candidates])
        return list(zip(*x))[0], list(zip(*x))[1]


def experiment_launcher(config):
    seed = config["seed"]

    # get the characteristics of the NN
    hostNodes = config["hostNodes"]
    guestNodes = config["guestNodes"]
    inputType = config["inputType"]
    updateType = config["updateType"]

    # archives
    means = []
    bests = []

    args = {}
    fka = HostMultipleNN(hostNodes, guestNodes, inputType, updateType)

    args["num_vars"] = fka.nweights * fka.guestnWeights # Number of dimensions of the search space
    args["max_generations"] = config["max_generations"]
    args["sigma"] = 1.0  # default standard deviation
    args["num_offspring"] = 20 #4 + int(math.floor(3 * math.log(fka.nweights)))  # lambda
    args["pop_size"] = 10 #int(math.floor(args["num_offspring"] / 2))  # mu
    args["pop_init_range"] = [-1, 1]  # Range for the initial population
    args["seed"] = seed


    random = Random()
    es = cmaes(generator(random, args),
               args["sigma"],
               {'popsize': args["num_offspring"],
                'seed': seed,
                'CMA_mu': args["pop_size"]})
    gen = 0
    logs = []
    final_weights = dict()

    best = [0,0,0]
    worst = [0,0,-500]

    while gen <= args["max_generations"]:
        candidates = es.ask()  # get list of new solutions
        fitnesses, all_weights = parallel_val(candidates, hostNodes, guestNodes, inputType, updateType)
        final_weights[gen] = all_weights
        print("generation "+str(gen)+"  "+str(fitnesses)+"  "+str(np.mean(fitnesses)))

        # to print weights
        if best[2] >= min(fitnesses):
          best[0] = gen
          best[1] = fitnesses.index(min(fitnesses))
          best[2] = min(fitnesses)

        if worst[2] <= max(fitnesses):
          worst[0] = gen
          worst[1] = fitnesses.index(max(fitnesses))
          worst[2] = max(fitnesses)

        with open(filename, "a") as f:
          print("generation "+str(gen)+"  "+str(fitnesses)+"  "+str(np.mean(fitnesses)), file=f)

        means.append(np.mean(fitnesses))
        bests.append(min(fitnesses))

        es.tell(candidates, fitnesses)
        gen += 1
    final_pop = np.asarray(es.ask())

    parallel_res, all_weights = parallel_val(candidates, hostNodes, guestNodes, inputType, updateType)

    final_weights[gen] = all_weights
    final_pop_fitnesses = np.asarray(parallel_res)

    best_guy = es.best.x
    best_fitness = es.best.f

    pickle_data = {"type": "multiple", "hostNodes": hostNodes, "guestNodes": guestNodes, "inputType": inputType, "updateType": updateType, "candidate": best_guy}

    with open("pkl/host_multiple_hostNN_"+str(best_fitness)+".pkl", "wb") as f:
        pickle.dump(pickle_data, f)

    return means, bests, final_weights, best, worst

if __name__ == "__main__":
    HostNodes = [4, 4, 2]
    GuestNodes =  [3, 3, 1] 
    inputType = "ID" # @param ["IDA", "ID", "A"]
    updateType = "W" # @param ["W", "deltaW"]

    seed = 0
    means, bests, all_weights, best, worst = experiment_launcher({"seed": seed, "hostNodes": HostNodes, "guestNodes": GuestNodes, 
                                                                  "inputType": inputType, "updateType": updateType,
                                                                  "max_generations": 5})

    plot_generations('Cartpole - Multiple NN compute W', means, bests)
    # plot worst
    plot_weights(all_weights, HostNodes, worst[0], worst[1], "Worst")
    plot_weights(all_weights, HostNodes, best[0], best[1], "Best")

    # plot best - could take come time
    # ani = plot_weights_gif(all_weights, HostNodes, best[0], best[1], "Best")
    # ani.save('animation.gif', writer='imagemagick', fps=30)